// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMz_DvkQ3ezX6RUuZWBNz9-V_jDh2Q9f4',
    appId: '1:654599038714:web:cebcc496be48f56b460b43',
    messagingSenderId: '654599038714',
    projectId: 'my-flutter-splitwise',
    authDomain: 'my-flutter-splitwise.firebaseapp.com',
    storageBucket: 'my-flutter-splitwise.firebasestorage.app',
    measurementId: 'G-F52WM9W9J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC70HR37gu26Ivtg5BG13IL9fRX40Udr6U',
    appId: '1:654599038714:android:9110831b6889c8a8460b43',
    messagingSenderId: '654599038714',
    projectId: 'my-flutter-splitwise',
    storageBucket: 'my-flutter-splitwise.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiSeBpcAVsaRe31GtBDrfMNMnK37B5BEE',
    appId: '1:654599038714:ios:adcffd5aab2ead74460b43',
    messagingSenderId: '654599038714',
    projectId: 'my-flutter-splitwise',
    storageBucket: 'my-flutter-splitwise.firebasestorage.app',
    iosBundleId: 'com.rachit.splitwise.splitwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiSeBpcAVsaRe31GtBDrfMNMnK37B5BEE',
    appId: '1:654599038714:ios:adcffd5aab2ead74460b43',
    messagingSenderId: '654599038714',
    projectId: 'my-flutter-splitwise',
    storageBucket: 'my-flutter-splitwise.firebasestorage.app',
    iosBundleId: 'com.rachit.splitwise.splitwise',
  );

}